name: Pylint_Filtering

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8  # Replace with the desired Python version

    - name: Install dependencies
      
      run:
        python -m pip install --upgrade pip
        # pip install -r requirements.txt  # Create a requirements.txt file if needed
    - name: Install linter
      run:
        pip install pylint
    - name: List directory contents
      run:  ls -al
    - name: utest_filtering.py
      run: pylint utest_filtering.py || exit 0  # Replace with the actual name of your Python script

    
